stapi-spec/stapi-fastapi

- .dockerignore
- .gitattributes
- .gitignore
- Dockerfile
- poetry.lock
- pyproject.toml
- stat_fastapi/lambda_handler.py
- stat_fastapi_test_backend/backend.py
> Adding Dockerfile and Lambda handler

- poetry.lock
- pyproject.toml
- stat_fastapi/models/opportunity.py
- stat_fastapi/types/filter.py
- stat_fastapi_test_backend/backend.py
- stat_fastapi_tle_backend/backend.py
- tests/conftest.py
- tests/datetime_interval_test.py
- tests/opportunity_test.py
Closes #22 
This PR uses pygeofilter to parse the cql2-json filter. We aren't doing anything with the parsed value, just using the parse for its validation.
> Switch to using cql2 filter

- stat_fastapi/api.py
- stat_fastapi/backend.py
- stat_fastapi/models/opportunity.py
- stat_fastapi_landsat/backend.py
- stat_fastapi_landsat/models.py
- stat_fastapi_test_backend/backend.py
- stat_fastapi_tle_backend/backend.py
- stat_fastapi_tle_backend/models.py
- stat_fastapi_tle_backend/repository.py
- tests/conftest.py
- tests/order_test.py
- `OpportunitySearch` is renamed to `OpportunityRequest`
- This change is a bit messy, since this class is used all over, but it's probably good to conform to the naming of the spec.
- `filters` field is moved from `OpportunityProperties` to `OpportunitiesRequest`
See current relevant spec [here](https://github.com/Element84/stat-api-spec/tree/main/opportunity#opportunity-request).
> Update Opportunity Models to Conform with Current STAT Spec

- stapi_fastapi_landsat/backend.py
Looks like this was an inadvertently missed comma, the result of which is that the two strings are concatenated rather than being separate list elements.
> fix: missing commas in landsat products conformsTo

- pyproject.toml
When running `poetry install --with dev`, after installing dependencies, and attempt to install stapi_fastapi results in a warning:
"stapi_fastapi is not a package."
Following that, attempting to `pip install -e .` results in failure to build installable wheels for stapi-fastapi.
This fix adds `stapi-fastapi` as a package in the pyproject.toml.
Credit @jkeifer for helping me with this fix.
> fixes pip install as editable package

- src/stapi_fastapi/routers/product_router.py
- src/stapi_fastapi/routers/root_router.py
Fixes tags on /products routes to be `Products` (as defined in the STAPI spec) instead of `Product` or undefined
> Fixes tags on /products routes to be Products instead of Product or undefined

- CHANGELOG.md
- bin/server.py
- src/stapi_fastapi/models/product.py
- src/stapi_fastapi/routers/product_router.py
- tests/conftest.py
- tests/opportunity_test.py
- tests/product_test.py
- https://github.com/stapi-spec/stapi-fastapi/issues/87 (does not fully complete this issue)
- https://github.com/stapi-spec/stapi-fastapi/issues/96
- https://github.com/stapi-spec/stapi-fastapi/issues/92
1. Add endpoint /product/{productId}/order-parameters
2. Add links in Product entity to order-parameters and constraints
> add product order-parameters endpoint and links

- CHANGELOG.md
- None
Release prep for v0.1.0
> CHANGELOG update for v0.1.0 release

- CHANGELOG.md
- src/stapi_fastapi/models/order.py
- n/a
1. change Order id to only allow string
> change Order id to only allow string

- CHANGELOG.md
- src/stapi_fastapi/routers/product_router.py
- tests/opportunity_test.py
- tests/order_test.py
- tests/product_test.py
- n/a
1. change create-order endpoint from .../order to .../orders to follow web API conventions, and match with changes from stapi-spec
> change create-order endpoint from .../order to .../orders to follow web API conventions

- src/stapi_fastapi/models/product.py
- n/a
copy product with pydantic model_copy instead of copy.deepcopy
I hit an error with this after some changes that I think monkeypatched a class. I don't know if the error is related to this or not, but it would be better to do this copy the Pydantic way rathe than the generic way.
> copy product with pydantic model_copy instead of copy.deepcopy

- CHANGELOG.md
- src/stapi_fastapi/models/conformance.py
- n/a
1. bump version to v0.2.0
> pre-release prep for v0.2.0

- CHANGELOG.md
- bin/server.py
- src/stapi_fastapi/backends/product_backend.py
- src/stapi_fastapi/backends/root_backend.py
- src/stapi_fastapi/models/order.py
- src/stapi_fastapi/models/product.py
- tests/backends.py
- n/a
1. replace enums extending `str, Enum` with StrEnum
2. replace `Result[A, Exception]` types with the alias `ResultE[A]`
> use StrEnum and ResultE types

- CHANGELOG.md
- src/stapi_fastapi/models/order.py
- n/a
1. refactor Order and OrderCollection to not extend Feature and FeatureCollection, to allow for tighter type constraints. This was a request from Jarrett.
> refactor Order and OrderCollection to not extend Feature and FeatureCollection

- src/stapi_fastapi/models/conformance.py
- n/a
1. Fix conformance URI versions that were accidentally set to 0.2.0 in the last release back to 0.1.0 to match the actual stapi-spec version
> fix conformance versions to 0.1.0 to match stapi-spec versions

- CHANGELOG.md
- src/stapi_fastapi/backends/product_backend.py
- src/stapi_fastapi/backends/root_backend.py
- src/stapi_fastapi/models/order.py
- src/stapi_fastapi/routers/product_router.py
- src/stapi_fastapi/routers/root_router.py
- tests/application.py
- tests/backends.py
- tests/conftest.py
- tests/test_order.py
- n/a
1. Endpoint `/orders/{order_id}/statuses` supporting `GET` for retrieving statuses. The entity returned by this conforms
to the change proposed in [stapi-spec#239](https://github.com/stapi-spec/stapi-spec/pull/239).
2. Endpoint `/orders/{order_id}/statuses` supporting `POST` for updating current status
3. RootBackend has new methods `get_order_statuses` and `set_order_status` to support those operations
4. OrderRequest renamed to OrderPayload
> add support for order statuses endpoints

- CHANGELOG.md
- src/stapi_fastapi/routers/root_router.py
- #
1. Allow configuring ProductRouter via `*args`/`**kwargs` support in RootRouter's `add_product` method for advanced use cases, i.e. overriding the APIRoute class used (that's our use case at SatVu)
> fix: add args/kwargs support in RootRouter.add_product to configure ProductRouter

- CHANGELOG.md
- n/a
1. update changelog for 0.5.0 release
> update changelog for release v0.5.0

- .github/workflows/python-publish.yml
- n/a
1. revert python-publish changes from PR 132. Looks like it was a copy/paste error
> revert python-publish changes from PR 132

- src/stapi_fastapi/backends/product_backend.py
- src/stapi_fastapi/backends/root_backend.py
- src/stapi_fastapi/routers/product_router.py
- src/stapi_fastapi/routers/root_router.py
- tests/backends.py
- n/a
1. In all the backend method signatures, make Request the last parameter, so that all more specific parameter values are before it.
> in backend methods, make Request the last parameter in all methods

- src/stapi_fastapi/models/opportunity.py
- src/stapi_fastapi/routers/product_router.py
- tests/test_opportunity.py
To meet the goal of having all pagination features fully contained within the POST body for `search_opportunities` the `OpportunityRequest` POST model has been updated to include a `limit` and 'next` field.  PR changes here are accounting for and handling the downstream effects of that model change - updating the endpoint and tests.
- #
1. Adding a `next` and `limit` field to the `OpportunityRequest` POST body model.
> Add pagination token + limit to OpportunityRequest model

- CHANGELOG.md
- src/stapi_fastapi/backends/product_backend.py
- src/stapi_fastapi/models/opportunity.py
- src/stapi_fastapi/routers/product_router.py
- src/stapi_fastapi/routers/root_router.py
- tests/application.py
- tests/backends.py
- tests/shared.py
- tests/test_opportunity.py
- tests/test_order.py
- tests/test_product.py
- https://github.com/stapi-spec/stapi-fastapi/issues/121
- add body to create-order link in Opportunities Search result
- refine pagination code
- rename OpportunityRequest to OpportunityPayload - this makes it so it won't be confused with the starlette/fastapi Request class and the Payload part aligns it with other POST body model names
> refine pagination code, other minor refinements
